## 데이터 셋 생성을 위한 코드

In [1]:
# library import 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import svm
from sklearn.preprocessing import PolynomialFeatures
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
# 표 전체 보기
print("pandas version: ", pd.__version__)
pd.set_option('display.max_row', 500)
pd.set_option('display.max_columns', 100)

pandas version:  1.3.5


In [3]:
# data read
# data read는 드라이브 마운트가 되어있기 때문에 각자의 경로로 수정해 주셔야 합니다.
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [4]:
# missing value processing
# median
train.fillna(train.median(), inplace=True)  #결측값 변경
test.fillna(train.median(), inplace=True)

# contry 열 삭제
train.drop(['country'], axis=1, inplace=True)
test.drop(['country'], axis=1, inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  after removing the cwd from sys.path.


In [5]:
display(train[:10])

index   Q1   Q2   Q3   Q4   Q5   Q6   Q7   Q8   Q9  Q10  Q11  Q12  Q13  \
0      0  1.0  5.0  5.0  5.0  1.0  4.0  5.0  5.0  1.0  3.0  5.0  5.0  5.0   
1      1  4.0  4.0  4.0  4.0  4.0  5.0  4.0  4.0  3.0  3.0  1.0  4.0  5.0   
2      2  4.0  5.0  5.0  4.0  3.0  5.0  5.0  5.0  4.0  4.0  2.0  5.0  5.0   
3      3  4.0  4.0  4.0  2.0  4.0  3.0  3.0  5.0  3.0  4.0  5.0  2.0  2.0   
4      4  4.0  4.0  4.0  4.0  3.0  3.0  4.0  2.0  3.0  4.0  4.0  4.0  3.0   
5      5  5.0  4.0  5.0  5.0  5.0  5.0  5.0  4.0  4.0  3.0  4.0  5.0  2.0   
6      6  4.0  3.0  4.0  3.0  5.0  4.0  5.0  4.0  5.0  5.0  3.0  5.0  5.0   
7      7  4.0  5.0  4.0  4.0  4.0  4.0  2.0  5.0  3.0  4.0  2.0  2.0  3.0   
8      8  4.0  4.0  3.0  4.0  4.0  5.0  4.0  3.0  3.0  4.0  4.0  4.0  3.0   
9      9  3.0  3.0  4.0  3.0  4.0  2.0  4.0  2.0  4.0  4.0  5.0  4.0  1.0   

   Q14  Q15  Q16  Q17  Q18  Q19  Q20  Q21  Q22  Q23  Q24  Q25  Q26  \
0  5.0  5.0  5.0  5.0  1.0  5.0  5.0  1.0  5.0  1.0  5.0  1.0  1.0   
1  3.0  1.0  2.0  4.0  5.0  1.0  3.0  1.0  1.0  5.0  3.0  2.0  5.0   
2  5.0  1.0  3.0  5.0  3.0  5.0  2.0  2.0  1.0  2.0  4.0  2.0  5.0   
3  4.0  4.0  2.0  4.0  5.0  4.0  3.0  3.0  4.0  3.0  4.0  4.0  2.0   
4  5.0  5.0  2.0  4.0  1.0  4.0  2.0  4.0  2.0  3.0  4.0  4.0  4.0   
5  3.0  4.0  1.0  1.0  2.0  4.0  2.0  2.0  2.0  3.0  5.0  3.0  5.0   
6  3.0  3.0  3.0  5.0  5.0  3.0  4.0  4.0  3.0  5.0  5.0  3.0  5.0   
7  3.0  5.0  2.0  4.0  5.0  2.0  3.0  5.0  3.0  5.0  5.0  1.0  4.0   
8  3.0  3.0  1.0  2.0  4.0  1.0  3.0  1.0  2.0  5.0  3.0  1.0  4.0   
9  4.0  2.0  5.0  4.0  4.0  5.0  3.0  1.0  1.0  2.0  4.0  4.0  2.0   

   introelapse  testelapse  surveyelapse  TIPI1  TIPI2  TIPI3  TIPI4  TIPI5  \
0            3         553             6    4.0    3.0    5.0    1.0    3.0   
1            5          85           120    4.0    2.0    3.0    5.0    3.0   
2            9         108           100    1.0    2.0    3.0    1.0    5.0   
3            2         121           139    3.0    3.0    3.0    4.0    5.0   
4            3         640           216    3.0    3.0    4.0    4.0    4.0   
5            3         100           176    5.0    3.0    3.0    3.0    5.0   
6           17          88           164    3.0    2.0    5.0    3.0    4.0   
7           20          53           112    3.0    2.0    5.0    5.0    3.0   
8            9         164           213    3.0    1.0    4.0    3.0    4.0   
9          109         134           177    2.0    2.0    5.0    3.0    3.0   

   TIPI6  TIPI7  TIPI8  TIPI9  TIPI10  VCL1  VCL2  VCL3  VCL4  VCL5  VCL6  \
0    5.0    5.0    3.0    5.0     3.0     1     1     0     1     1     0   
1    2.0    5.0    1.0    2.0     2.0     1     1     1     1     1     0   
2    5.0    3.0    4.0    5.0     2.0     1     1     0     1     1     0   
3    3.0    4.0    4.0    3.0     3.0     1     1     0     1     1     0   
4    4.0    3.0    4.0    3.0     2.0     1     1     0     1     1     0   
5    2.0    4.0    5.0    3.0     1.0     1     1     0     1     1     0   
6    3.0    3.0    2.0    3.0     2.0     1     1     0     1     1     0   
7    3.0    3.0    2.0    2.0     2.0     1     1     1     1     0     0   
8    3.0    4.0    1.0    3.0     3.0     1     1     1     1     1     1   
9    4.0    4.0    2.0    4.0     4.0     1     1     0     1     1     0   

   VCL7  VCL8  VCL9  VCL10  VCL11  VCL12  VCL13  VCL14  VCL15  VCL16  \
0     0     0     0      1      0      0      0      1      1      1   
1     1     0     0      1      0      0      1      1      1      1   
2     1     1     0      1      0      0      1      1      1      1   
3     0     0     0      1      0      0      1      1      1      1   
4     0     1     0      1      0      0      0      1      0      1   
5     0     1     0      1      0      0      1      1      1      1   
6     0     0     0      1      0      0      1      1      1      1   
7     0     1     0      1      1      0      1      1      1      1   
8     0     0     

In [6]:
# train_data_split
train_input = train.iloc[:, :-1]
train_target = train.iloc[:, -1]

In [7]:
display(train_input[:10])

index   Q1   Q2   Q3   Q4   Q5   Q6   Q7   Q8   Q9  Q10  Q11  Q12  Q13  \
0      0  1.0  5.0  5.0  5.0  1.0  4.0  5.0  5.0  1.0  3.0  5.0  5.0  5.0   
1      1  4.0  4.0  4.0  4.0  4.0  5.0  4.0  4.0  3.0  3.0  1.0  4.0  5.0   
2      2  4.0  5.0  5.0  4.0  3.0  5.0  5.0  5.0  4.0  4.0  2.0  5.0  5.0   
3      3  4.0  4.0  4.0  2.0  4.0  3.0  3.0  5.0  3.0  4.0  5.0  2.0  2.0   
4      4  4.0  4.0  4.0  4.0  3.0  3.0  4.0  2.0  3.0  4.0  4.0  4.0  3.0   
5      5  5.0  4.0  5.0  5.0  5.0  5.0  5.0  4.0  4.0  3.0  4.0  5.0  2.0   
6      6  4.0  3.0  4.0  3.0  5.0  4.0  5.0  4.0  5.0  5.0  3.0  5.0  5.0   
7      7  4.0  5.0  4.0  4.0  4.0  4.0  2.0  5.0  3.0  4.0  2.0  2.0  3.0   
8      8  4.0  4.0  3.0  4.0  4.0  5.0  4.0  3.0  3.0  4.0  4.0  4.0  3.0   
9      9  3.0  3.0  4.0  3.0  4.0  2.0  4.0  2.0  4.0  4.0  5.0  4.0  1.0   

   Q14  Q15  Q16  Q17  Q18  Q19  Q20  Q21  Q22  Q23  Q24  Q25  Q26  \
0  5.0  5.0  5.0  5.0  1.0  5.0  5.0  1.0  5.0  1.0  5.0  1.0  1.0   
1  3.0  1.0  2.0  4.0  5.0  1.0  3.0  1.0  1.0  5.0  3.0  2.0  5.0   
2  5.0  1.0  3.0  5.0  3.0  5.0  2.0  2.0  1.0  2.0  4.0  2.0  5.0   
3  4.0  4.0  2.0  4.0  5.0  4.0  3.0  3.0  4.0  3.0  4.0  4.0  2.0   
4  5.0  5.0  2.0  4.0  1.0  4.0  2.0  4.0  2.0  3.0  4.0  4.0  4.0   
5  3.0  4.0  1.0  1.0  2.0  4.0  2.0  2.0  2.0  3.0  5.0  3.0  5.0   
6  3.0  3.0  3.0  5.0  5.0  3.0  4.0  4.0  3.0  5.0  5.0  3.0  5.0   
7  3.0  5.0  2.0  4.0  5.0  2.0  3.0  5.0  3.0  5.0  5.0  1.0  4.0   
8  3.0  3.0  1.0  2.0  4.0  1.0  3.0  1.0  2.0  5.0  3.0  1.0  4.0   
9  4.0  2.0  5.0  4.0  4.0  5.0  3.0  1.0  1.0  2.0  4.0  4.0  2.0   

   introelapse  testelapse  surveyelapse  TIPI1  TIPI2  TIPI3  TIPI4  TIPI5  \
0            3         553             6    4.0    3.0    5.0    1.0    3.0   
1            5          85           120    4.0    2.0    3.0    5.0    3.0   
2            9         108           100    1.0    2.0    3.0    1.0    5.0   
3            2         121           139    3.0    3.0    3.0    4.0    5.0   
4            3         640           216    3.0    3.0    4.0    4.0    4.0   
5            3         100           176    5.0    3.0    3.0    3.0    5.0   
6           17          88           164    3.0    2.0    5.0    3.0    4.0   
7           20          53           112    3.0    2.0    5.0    5.0    3.0   
8            9         164           213    3.0    1.0    4.0    3.0    4.0   
9          109         134           177    2.0    2.0    5.0    3.0    3.0   

   TIPI6  TIPI7  TIPI8  TIPI9  TIPI10  VCL1  VCL2  VCL3  VCL4  VCL5  VCL6  \
0    5.0    5.0    3.0    5.0     3.0     1     1     0     1     1     0   
1    2.0    5.0    1.0    2.0     2.0     1     1     1     1     1     0   
2    5.0    3.0    4.0    5.0     2.0     1     1     0     1     1     0   
3    3.0    4.0    4.0    3.0     3.0     1     1     0     1     1     0   
4    4.0    3.0    4.0    3.0     2.0     1     1     0     1     1     0   
5    2.0    4.0    5.0    3.0     1.0     1     1     0     1     1     0   
6    3.0    3.0    2.0    3.0     2.0     1     1     0     1     1     0   
7    3.0    3.0    2.0    2.0     2.0     1     1     1     1     0     0   
8    3.0    4.0    1.0    3.0     3.0     1     1     1     1     1     1   
9    4.0    4.0    2.0    4.0     4.0     1     1     0     1     1     0   

   VCL7  VCL8  VCL9  VCL10  VCL11  VCL12  VCL13  VCL14  VCL15  VCL16  \
0     0     0     0      1      0      0      0      1      1      1   
1     1     0     0      1      0      0      1      1      1      1   
2     1     1     0      1      0      0      1      1      1      1   
3     0     0     0      1      0      0      1      1      1      1   
4     0     1     0      1      0      0      0      1      0      1   
5     0     1     0      1      0      0      1      1      1      1   
6     0     0     0      1      0      0      1      1      1      1   
7     0     1     0      1      1      0      1      1      1      1   
8     0     0     

In [8]:
display(train_target[:10])

0    1
1    1
2    1
3    1
4    0
5    1
6    1
7    1
8    0
9    0
Name: nerdiness, dtype: int64

### Standard Scaler

In [9]:
# standard scaler
def scaler(dataset):
  scaler = StandardScaler()
  out = scaler.fit_transform(dataset)
  return out

In [10]:
# # # 평균 0, 분산 1을 갖도록 스케일 조정

# # scaler = StandardScaler()
# # scaler.fit(X_train)
# # X_train_scaled = scaler.transform(X_train)
# # X_test_scaled = scaler.transform(X_test)

# # 조정된 데이터로 SVM 학습
# svm.fit(X_train_scaled, y_train)

# # 스케일 조정된 테스트 세트의 정확도
# print(svm.score(X_test_scaled, y_test))

In [11]:
# full data generate function
def full_data(dataset):
  full_data = pd.get_dummies(dataset, columns=['gender', 'hand', 'religion', 'orientation', 'voted', 'married', 'ASD'], drop_first=True)
  full_data = scaler(full_data)
  return full_data

In [12]:
display(full_data)

<function __main__.full_data(dataset)>

In [13]:
# feature Engineering - MV data
def MV_data(dataset):
  MV_data = dataset.iloc[:, [1,2,3,4,5,7,8,9,10,11,12,13,15,16,17,19,20]]

  for i in [3,7,10,16,4,11,17,9]:
    MV_data['Q' + str(i)] = 6 - MV_data['Q' + str(i)]

  MV_data['score'] = np.sum(MV_data, axis=1)

  MV_data = scaler(MV_data)

  return MV_data

In [14]:
# survey data - Q1~Q26
def survey_data(dataset):
  survey_data = dataset.iloc[:, 1:26]
  survey_data = scaler(survey_data)
  return survey_data

In [15]:
# pca data - maximized dimention about input data and decrese of dimention
# input : survey data
def pca_data(dataset):
  poly = PolynomialFeatures(include_bias=False, degree=2)
  poly_data = poly.fit_transform(dataset)

  pca = PCA(n_components=50)
  pca_data = pca.fit_transform(poly_data)
  # pca_data = scaler(pca_data)
  return pca_data

In [16]:
print(MV_data)
print(survey_data)
print(pca_data)

<function MV_data at 0x7f89778abe60>
<function survey_data at 0x7f89778ad3b0>
<function pca_data at 0x7f89778ada70>


In [17]:
pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## 모델 개발
- 모델은 각 데이터 셋 별로 3개씩 생성
  - XGBoost
  - LGBM
  - RandomForestClassifier

In [18]:
# 모델 생성 및 예측을 자동을 수행하는 함수를 생성
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier, Pool

def model_fit_predict(dataset, targetdata, testset):
  model1 = RandomForestClassifier()
  model2 = XGBClassifier(n_estimators=2000, learning_rate=0.03, max_depth=20)
  model3 = LGBMClassifier(n_estimators=2000, max_depth=20)
  model4 = CatBoostClassifier(iterations=2, depth=7, learning_rate=0.03, 
                              loss_function='Logloss', verbose=True)


  # for model in [model1, model2, model3]:
  #   model.fit(dataset,targetdata)
  
  # fit
  model1.fit(dataset,targetdata)
  model2.fit(dataset,targetdata)
  model3.fit(dataset,targetdata)
  model4.fit(dataset,targetdata)
    
  # predict
  pred1 = model1.predict(testset)
  pred2 = model2.predict(testset)
  pred3 = model3.predict(testset)
  pred4 = model4.predict(testset)

  pred_sum = pred1 + pred2 + pred3 + pred4

  # hard voting ensemble
  predict_final = []
  for pred in pred_sum:
    if pred > 2:
      predict_final.append(1)
    else:
      predict_final.append(0)

  return np.array(predict_final)

## 하이퍼파라미터 튜닝

### model 생성

In [19]:
# 데이터 만들어내기
full_data_train = full_data(train_input)
full_data_test = full_data(test)

MV_data_train = MV_data(train_input)
MV_data_test = MV_data(test)

survey_data_train = survey_data(train_input)
survey_data_test = survey_data(test)

pca_data_train = pca_data(survey_data_train)
pca_data_test = pca_data(survey_data_test)

# catboost_data_train = 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/s

### 모델 생성 1개씩 찍어내자

In [20]:
model1_pred = model_fit_predict(full_data_train, train_target, full_data_test)

0:	learn: 0.6852862	total: 57.1ms	remaining: 57.1ms
1:	learn: 0.6777591	total: 65.9ms	remaining: 0us


In [21]:
model2_pred = model_fit_predict(MV_data_train, train_target, MV_data_test)

0:	learn: 0.6878182	total: 2.76ms	remaining: 2.76ms
1:	learn: 0.6828444	total: 5.15ms	remaining: 0us


In [22]:
model3_pred = model_fit_predict(survey_data_train, train_target, survey_data_test)

0:	learn: 0.6856783	total: 4.69ms	remaining: 4.69ms
1:	learn: 0.6781057	total: 8.85ms	remaining: 0us


In [23]:
model4_pred = model_fit_predict(pca_data_train, train_target, pca_data_test)

0:	learn: 0.6867483	total: 23.1ms	remaining: 23.1ms
1:	learn: 0.6803395	total: 48.1ms	remaining: 0us


In [24]:
# #catboost
# model5_pred = model_fit_predict(full_data_train, train_target, full_data_test)

### 딥러닝 모델 추가

In [26]:
from tensorflow import keras

# deep_model1 with full_data
deep_model1 = keras.Sequential()
deep_model1.add(keras.layers.Dense(128, activation='leaky_relu', input_shape=(84,)))
deep_model1.add(keras.layers.Dropout(0.3))
deep_model1.add(keras.layers.Dense(64, activation='leaky_relu'))
deep_model1.add(keras.layers.Dropout(0.2))
deep_model1.add(keras.layers.Dense(32, activation='leaky_relu'))
deep_model1.add(keras.layers.Dense(16, activation='leaky_relu'))
deep_model1.add(keras.layers.Dense(8, activation='leaky_relu'))
deep_model1.add(keras.layers.Dense(8, activation='leaky_relu'))
deep_model1.add(keras.layers.Dense(1, activation='sigmoid'))

# fit
deep_model1.compile(loss=keras.losses.binary_crossentropy, optimizer='adam', metrics='accuracy')
deep_model1.fit(full_data_train, train_target, epochs=200)

Epoch 1/200
469/469 [==============================] - 2s 3ms/step - loss: 0.5722 - accuracy: 0.7083
Epoch 2/200
469/469 [==============================] - 1s 3ms/step - loss: 0.5470 - accuracy: 0.7262
Epoch 3/200
469/469 [==============================] - 1s 1ms/step - loss: 0.5366 - accuracy: 0.7303
Epoch 4/200
469/469 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7359
Epoch 5/200
469/469 [==============================] - 1s 3ms/step - loss: 0.5303 - accuracy: 0.7353
Epoch 6/200
469/469 [==============================] - 1s 2ms/step - loss: 0.5236 - accuracy: 0.7360
Epoch 7/200
469/469 [==============================] - 1s 3ms/step - loss: 0.5195 - accuracy: 0.7435
Epoch 8/200
469/469 [==============================] - 2s 3ms/step - loss: 0.5156 - accuracy: 0.7471
Epoch 9/200
469/469 [==============================] - 1s 3ms/step - loss: 0.5105 - accuracy: 0.7489
Epoch 10/200
469/469 [==============================] - 1s 2ms/step - loss: 0.5072 - accura

In [27]:
np.round(deep_model1.predict(full_data_test))[:10]

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [28]:
# deep_model2 with _MV_data
deep_model2 = keras.Sequential()
deep_model2.add(keras.layers.Dense(64, activation='leaky_relu', input_shape=(18,)))
deep_model2.add(keras.layers.Dropout(0.3))
deep_model2.add(keras.layers.Dense(32, activation='leaky_relu'))
deep_model2.add(keras.layers.Dropout(0.2))
deep_model2.add(keras.layers.Dense(16, activation='leaky_relu'))
deep_model2.add(keras.layers.Dense(8, activation='leaky_relu'))
deep_model2.add(keras.layers.Dense(4, activation='leaky_relu'))
deep_model2.add(keras.layers.Dense(2, activation='leaky_relu'))
deep_model2.add(keras.layers.Dense(1, activation='sigmoid'))

# fit
deep_model2.compile(loss=keras.losses.binary_crossentropy, optimizer='adam', metrics='accuracy')
deep_model2.fit(MV_data_train, train_target, epochs=100)

Epoch 1/100
469/469 [==============================] - 1s 1ms/step - loss: 0.6001 - accuracy: 0.6845
Epoch 2/100
469/469 [==============================] - 1s 1ms/step - loss: 0.5755 - accuracy: 0.7031
Epoch 3/100
469/469 [==============================] - 1s 1ms/step - loss: 0.5719 - accuracy: 0.7029
Epoch 4/100
469/469 [==============================] - 1s 1ms/step - loss: 0.5691 - accuracy: 0.7043
Epoch 5/100
469/469 [==============================] - 1s 1ms/step - loss: 0.5683 - accuracy: 0.7039
Epoch 6/100
469/469 [==============================] - 1s 1ms/step - loss: 0.5682 - accuracy: 0.7077
Epoch 7/100
469/469 [==============================] - 1s 1ms/step - loss: 0.5676 - accuracy: 0.7069
Epoch 8/100
469/469 [==============================] - 1s 1ms/step - loss: 0.5659 - accuracy: 0.7095
Epoch 9/100
469/469 [==============================] - 1s 1ms/step - loss: 0.5655 - accuracy: 0.7074
Epoch 10/100
469/469 [==============================] - 1s 1ms/step - loss: 0.5646 - accura

In [30]:
# deep_model3 with survey_data
deep_model3 = keras.Sequential()
deep_model3.add(keras.layers.Dense(16, activation='leaky_relu', input_shape=(25,)))
deep_model2.add(keras.layers.Dropout(0.2))
deep_model3.add(keras.layers.Dense(8, activation='leaky_relu'))
deep_model3.add(keras.layers.Dense(4, activation='leaky_relu'))
deep_model3.add(keras.layers.Dense(1, activation='sigmoid'))

# fit
deep_model3.compile(loss=keras.losses.binary_crossentropy, optimizer='adam', metrics='accuracy')
deep_model3.fit(survey_data_train, train_target, epochs=50)

Epoch 1/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5761 - accuracy: 0.6981
Epoch 2/50
469/469 [==============================] - 0s 984us/step - loss: 0.5506 - accuracy: 0.7189
Epoch 3/50
469/469 [==============================] - 0s 982us/step - loss: 0.5464 - accuracy: 0.7237
Epoch 4/50
469/469 [==============================] - 0s 1ms/step - loss: 0.5432 - accuracy: 0.7253
Epoch 5/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7267
Epoch 6/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7310
Epoch 7/50
469/469 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7311
Epoch 8/50
469/469 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7334
Epoch 9/50
469/469 [==============================] - 0s 963us/step - loss: 0.5349 - accuracy: 0.7355
Epoch 10/50
469/469 [==============================] - 0s 957us/step - loss: 0.5343 - accuracy

In [31]:
# deep_model4 with pca_data
deep_model4 = keras.Sequential()
deep_model4.add(keras.layers.Dense(32, activation='leaky_relu', input_shape=(50,)))
deep_model4.add(keras.layers.Dropout(0.2))
deep_model4.add(keras.layers.Dense(16, activation='leaky_relu'))
deep_model4.add(keras.layers.Dense(8, activation='leaky_relu'))
deep_model4.add(keras.layers.Dense(4, activation='leaky_relu'))
deep_model4.add(keras.layers.Dense(2, activation='leaky_relu'))
deep_model4.add(keras.layers.Dense(1, activation='sigmoid'))

# fit
deep_model4.compile(loss=keras.losses.binary_crossentropy, optimizer='adam', metrics='accuracy')
deep_model4.fit(pca_data_train, train_target, epochs=50)

Epoch 1/50
469/469 [==============================] - 1s 1ms/step - loss: 0.6340 - accuracy: 0.6383
Epoch 2/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5791 - accuracy: 0.6911
Epoch 3/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5673 - accuracy: 0.6979
Epoch 4/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5617 - accuracy: 0.7011
Epoch 5/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.7069
Epoch 6/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5545 - accuracy: 0.7061
Epoch 7/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7106
Epoch 8/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7109
Epoch 9/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7123
Epoch 10/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5459 - accuracy: 0.7129

In [ ]:
# from tensorflow import keras

# # deep_model5 with full_data
# deep_model5 = keras.Sequential()
# deep_model5.add(keras.layers.Dense(128, activation='elu', input_shape=(84,)))
# deep_model5.add(keras.layers.Dropout(0.3))
# deep_model5.add(keras.layers.Dense(64, activation='elu'))
# deep_model5.add(keras.layers.Dropout(0.3))
# deep_model5.add(keras.layers.Dense(32, activation='elu'))
# deep_model5.add(keras.layers.Dense(16, activation='elu'))
# deep_model5.add(keras.layers.Dense(8, activation='elu'))
# deep_model5.add(keras.layers.Dense(4, activation='elu'))
# deep_model5.add(keras.layers.Dense(1, activation='sigmoid'))

# # fit
# deep_model5.compile(loss=keras.losses.binary_crossentropy, optimizer='adam', metrics='accuracy')
# deep_model5.fit(full_data_train, train_target, epochs=200)

In [32]:
# ensemble
def deep_result():
  final_pred = []
  preds = np.round(deep_model1.predict(full_data_test)) + np.round(deep_model2.predict(MV_data_test)) + np.round(deep_model3.predict(survey_data_test)) 
  + np.round(deep_model4.predict(pca_data_test))

  for pred in preds:
    if pred >= 2:
      final_pred.append(1)
    else:
      final_pred.append(0)
  
  return np.array(final_pred)

In [33]:
deep_result = deep_result()

In [34]:
deep_result[:30]

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0])

### 찍어낸 모델 테스트

In [35]:
# 모델이 예측한 값들을 찍어보는 코드

# 일단 model4는 당시 사용을 안해서 일단은 주석처리를 해 두었다.
print(model1_pred[:10])
print(model2_pred[:10])
print(model3_pred[:10])
print(model4_pred[:10])
# print(model5_pred[:10])  #이게 catboost

[0 1 1 1 1 0 1 1 0 0]
[0 1 1 1 1 0 1 1 1 0]
[0 1 1 1 1 0 1 1 0 0]
[1 1 1 0 1 0 1 1 0 0]


In [36]:
# 딥러닝 예측 모델 deep_model1만 사용했다.
# 딥러닝 모델을 사용하고 싶다면 다른 것들을 추가해도 됩니다.
deep_model1_pred = np.round(deep_model1.predict(full_data_test))
deep_model1_pred = deep_model1_pred.reshape(-1)

In [37]:
preds = model1_pred + model2_pred + model3_pred + model4_pred #+ model5_pred

In [38]:
preds

array([1, 4, 4, ..., 3, 1, 3])

In [39]:
# 최종 모델의 결정을 위한 앙상블 학습
# hard voting ensemble
predict_final = []
for pred in preds:
  if pred >= 1.5:
    predict_final.append(1)
  else:
    predict_final.append(0)

result = np.array(predict_final)

In [ ]:
# # soft voting ensemble 근데 이 모델에서 soft voting이 가능한가
# predict_final2 = []
# for pred in preds:
#   if pred/3 >= 0.6:
#     predict_final2.append(1)
#   else:
#     predict_final2.append(0)

# result2 = np.array(predict_final2)

## 하이퍼파라미터 튜닝

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error

# params = {'min_impurity_decrease':np.arrange(0.0001, 0,001, 0.0001), 'max_depth': range(5,20,1), 'min_samples_split':range(2.100,10)}
# dtree = DecisionTreeClassifier()

# grid_search = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
# grid_search(params={'n_estimators':[100,200,400,800,1600,2400]})

rmse_scores = []
estimators = []

rf = RandomForestRegressor(warm_start=True, n_jobs=-1, random_state=2)
est=10

# for i in range(21):
#   rf.set_params(n_estimators=set)
#   rf.fit(model1_pred, test)
#   rmse = mean_squared_error(model1_pred, rf.predict(test), squared=False)
#   rmse_scores.append(rmse)
#   estimators.append(est)

#   est +=25

plt.figure(figsize=(15,7))
plt.plot(estimators, rmse_scores)
plt.xlabel('Number of Trees')
plt.ylabel('Rmse')
plt.title('Random Forest', fontsize=15)

plt.show()

### 성능 검사

In [ ]:
# print(pred_sum)

## 제출 파일 생성

In [47]:
# 제출 파일 생성
submission = pd.read_csv('sample_submission.csv')
submission['nerdiness'] = result

# 생성된 CSV 파일 저장하는 코드
# 코랩에서 작업시 작업 디렉터리에 생성되며 이를 로컬로 다운 받아 제출을 해 주어야 한다.
submission.to_csv("submission_yk6.csv", index = False)